version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

  deploy:
    docker:
      - image: simonmassey/gitops-openshift:latest
    working_directory: ~/circleci-demo-workflows
    environment:
      OPENSHIFT_SERVER: "${OPENSHIFT_SERVER}"
      OPENSHIFT_USER: "${OPENSHIFT_USER}"
      OPENSHIFT_PASSWORD: "${OPENSHIFT_PASSWORD}"
      CIRCLE_TAG: "${CIRCLE_TAG}"
    steps:
      - checkout
      - run:
          command: |
            "echo $${CIRCLE_TAG} ${OPENSHIFT_SERVER} ${OPENSHIFT_USER} "

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
#            branches:
#              ignore: /.*/