version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: simonmassey/gitops-openshift:20180626_1821
    working_directory: ~/circleci-demo-workflows
    environment:
      BUILD_NAMESPACE: "hubot"
      BUILD: "openshiftbot"
    steps:
      - run:
          command: |
            "export TAG=${CIRCLE_TAG} ; trigger-oc-build.sh"

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/